// generated by genptr.py, do not modify
#include "g_local.h"
#include "g_ptrs.h"
extern bool M_CheckAttack(edict_t *);
extern void AngleMove_Begin(edict_t *);
extern void AngleMove_Done(edict_t *);
extern void AngleMove_Final(edict_t *);
extern void barrel_delay(edict_t *, edict_t *, edict_t *, int, vec3_t);
extern void barrel_explode(edict_t *);
extern void barrel_touch(edict_t *, edict_t *, cplane_t *, csurface_t *);
extern void bfg_explode(edict_t *);
extern void bfg_think(edict_t *);
extern void bfg_touch(edict_t *, edict_t *, cplane_t *, csurface_t *);
extern void blaster_touch(edict_t *, edict_t *, cplane_t *, csurface_t *);
extern void body_die(edict_t *, edict_t *, edict_t *, int, vec3_t);
extern void button_done(edict_t *);
extern void button_killed(edict_t *, edict_t *, edict_t *, int, vec3_t);
extern void button_return(edict_t *);
extern void button_touch(edict_t *, edict_t *, cplane_t *, csurface_t *);
extern void button_use(edict_t *, edict_t *, edict_t *);
extern void button_wait(edict_t *);
extern void commander_body_drop(edict_t *);
extern void commander_body_think(edict_t *);
extern void commander_body_use(edict_t *, edict_t *, edict_t *);
extern void CTFGrappleTouch(edict_t *, edict_t *, cplane_t *, csurface_t *);
extern void debris_die(edict_t *, edict_t *, edict_t *, int, vec3_t);
extern void door_blocked(edict_t *, edict_t *);
extern void door_go_down(edict_t *);
extern void door_hit_bottom(edict_t *);
extern void door_hit_top(edict_t *);
extern void door_killed(edict_t *, edict_t *, edict_t *, int, vec3_t);
extern void door_secret_blocked(edict_t *, edict_t *);
extern void door_secret_die(edict_t *, edict_t *, edict_t *, int, vec3_t);
extern void door_secret_done(edict_t *);
extern void door_secret_move1(edict_t *);
extern void door_secret_move2(edict_t *);
extern void door_secret_move3(edict_t *);
extern void door_secret_move4(edict_t *);
extern void door_secret_move5(edict_t *);
extern void door_secret_move6(edict_t *);
extern void door_secret_use(edict_t *, edict_t *, edict_t *);
extern void door_touch(edict_t *, edict_t *, cplane_t *, csurface_t *);
extern void door_use(edict_t *, edict_t *, edict_t *);
extern void DoRespawn(edict_t *);
extern void drop_make_touchable(edict_t *);
extern void drop_temp_touch(edict_t *, edict_t *, cplane_t *, csurface_t *);
extern void droptofloor(edict_t *);
extern void flymonster_start_go(edict_t *);
extern void func_clock_think(edict_t *);
extern void func_clock_use(edict_t *, edict_t *, edict_t *);
extern void func_conveyor_use(edict_t *, edict_t *, edict_t *);
extern void func_explosive_explode(edict_t *, edict_t *, edict_t *, int, vec3_t);
extern void func_explosive_spawn(edict_t *, edict_t *, edict_t *);
extern void func_explosive_use(edict_t *, edict_t *, edict_t *);
extern void func_object_release(edict_t *);
extern void func_object_touch(edict_t *, edict_t *, cplane_t *, csurface_t *);
extern void func_object_use(edict_t *, edict_t *, edict_t *);
extern void func_timer_think(edict_t *);
extern void func_timer_use(edict_t *, edict_t *, edict_t *);
extern void func_train_find(edict_t *);
extern void func_wall_use(edict_t *, edict_t *, edict_t *);
extern void G_FreeEdict(edict_t *);
extern void gib_die(edict_t *, edict_t *, edict_t *, int, vec3_t);
extern void gib_think(edict_t *);
extern void gib_touch(edict_t *, edict_t *, cplane_t *, csurface_t *);
extern void Grenade_Explode(edict_t *);
extern void Grenade_Touch(edict_t *, edict_t *, cplane_t *, csurface_t *);
extern void hurt_touch(edict_t *, edict_t *, cplane_t *, csurface_t *);
extern void hurt_use(edict_t *, edict_t *, edict_t *);
extern void light_use(edict_t *, edict_t *, edict_t *);
extern void M_droptofloor(edict_t *);
extern void M_FliesOff(edict_t *);
extern void M_FliesOn(edict_t *);
extern void MegaHealth_think(edict_t *);
extern void misc_banner_think(edict_t *);
extern void misc_blackhole_think(edict_t *);
extern void misc_blackhole_use(edict_t *, edict_t *, edict_t *);
extern void misc_deadsoldier_die(edict_t *, edict_t *, edict_t *, int, vec3_t);
extern void misc_easterchick2_think(edict_t *);
extern void misc_easterchick_think(edict_t *);
extern void misc_eastertank_think(edict_t *);
extern void misc_satellite_dish_think(edict_t *);
extern void misc_satellite_dish_use(edict_t *, edict_t *, edict_t *);
extern void misc_strogg_ship_use(edict_t *, edict_t *, edict_t *);
extern void misc_viper_bomb_prethink(edict_t *);
extern void misc_viper_bomb_touch(edict_t *, edict_t *, cplane_t *, csurface_t *);
extern void misc_viper_bomb_use(edict_t *, edict_t *, edict_t *);
extern void misc_viper_use(edict_t *, edict_t *, edict_t *);
extern void monster_think(edict_t *);
extern void monster_triggered_spawn(edict_t *);
extern void monster_triggered_spawn_use(edict_t *, edict_t *, edict_t *);
extern void monster_use(edict_t *, edict_t *, edict_t *);
extern void Move_Begin(edict_t *);
extern void Move_Done(edict_t *);
extern void Move_Final(edict_t *);
extern void multi_wait(edict_t *);
extern void path_corner_touch(edict_t *, edict_t *, cplane_t *, csurface_t *);
extern void plat_blocked(edict_t *, edict_t *);
extern void plat_go_down(edict_t *);
extern void plat_hit_bottom(edict_t *);
extern void plat_hit_top(edict_t *);
extern void player_die(edict_t *, edict_t *, edict_t *, int, vec3_t);
extern void player_pain(edict_t *, edict_t *, float, int);
extern void point_combat_touch(edict_t *, edict_t *, cplane_t *, csurface_t *);
extern void rocket_touch(edict_t *, edict_t *, cplane_t *, csurface_t *);
extern void rotating_blocked(edict_t *, edict_t *);
extern void rotating_touch(edict_t *, edict_t *, cplane_t *, csurface_t *);
extern void rotating_use(edict_t *, edict_t *, edict_t *);
extern void SP_CreateCoopSpots(edict_t *);
extern void SP_FixCoopSpots(edict_t *);
extern void swimmonster_start_go(edict_t *);
extern void target_crosslevel_target_think(edict_t *);
extern void target_earthquake_think(edict_t *);
extern void target_earthquake_use(edict_t *, edict_t *, edict_t *);
extern void target_explosion_explode(edict_t *);
extern void target_laser_start(edict_t *);
extern void target_laser_think(edict_t *);
extern void target_laser_use(edict_t *, edict_t *, edict_t *);
extern void target_lightramp_think(edict_t *);
extern void target_lightramp_use(edict_t *, edict_t *, edict_t *);
extern void target_string_use(edict_t *, edict_t *, edict_t *);
extern void teleporter_touch(edict_t *, edict_t *, cplane_t *, csurface_t *);
extern void TH_viewthing(edict_t *);
extern void Think_AccelMove(edict_t *);
extern void Think_CalcMoveSpeed(edict_t *);
extern void Think_Delay(edict_t *);
extern void Think_SpawnDoorTrigger(edict_t *);
extern void Touch_DoorTrigger(edict_t *, edict_t *, cplane_t *, csurface_t *);
extern void Touch_Item(edict_t *, edict_t *, cplane_t *, csurface_t *);
extern void Touch_Multi(edict_t *, edict_t *, cplane_t *, csurface_t *);
extern void Touch_Plat_Center(edict_t *, edict_t *, cplane_t *, csurface_t *);
extern void train_blocked(edict_t *, edict_t *);
extern void train_next(edict_t *);
extern void train_use(edict_t *, edict_t *, edict_t *);
extern void train_wait(edict_t *);
extern void trigger_counter_use(edict_t *, edict_t *, edict_t *);
extern void trigger_crosslevel_trigger_use(edict_t *, edict_t *, edict_t *);
extern void trigger_elevator_init(edict_t *);
extern void trigger_elevator_use(edict_t *, edict_t *, edict_t *);
extern void trigger_enable(edict_t *, edict_t *, edict_t *);
extern void trigger_gravity_touch(edict_t *, edict_t *, cplane_t *, csurface_t *);
extern void trigger_key_use(edict_t *, edict_t *, edict_t *);
extern void trigger_monsterjump_touch(edict_t *, edict_t *, cplane_t *, csurface_t *);
extern void trigger_push_touch(edict_t *, edict_t *, cplane_t *, csurface_t *);
extern void trigger_relay_use(edict_t *, edict_t *, edict_t *);
extern void turret_blocked(edict_t *, edict_t *);
extern void turret_breach_finish_init(edict_t *);
extern void turret_breach_think(edict_t *);
extern void turret_driver_die(edict_t *, edict_t *, edict_t *, int, vec3_t);
extern void turret_driver_link(edict_t *);
extern void turret_driver_think(edict_t *);
extern void Use_Areaportal(edict_t *, edict_t *, edict_t *);
extern void Use_Item(edict_t *, edict_t *, edict_t *);
extern void use_killbox(edict_t *, edict_t *, edict_t *);
extern void Use_Multi(edict_t *, edict_t *, edict_t *);
extern void Use_Plat(edict_t *, edict_t *, edict_t *);
extern void use_target_blaster(edict_t *, edict_t *, edict_t *);
extern void use_target_changelevel(edict_t *, edict_t *, edict_t *);
extern void use_target_explosion(edict_t *, edict_t *, edict_t *);
extern void use_target_goal(edict_t *, edict_t *, edict_t *);
extern void Use_Target_Help(edict_t *, edict_t *, edict_t *);
extern void use_target_secret(edict_t *, edict_t *, edict_t *);
extern void use_target_spawner(edict_t *, edict_t *, edict_t *);
extern void Use_Target_Speaker(edict_t *, edict_t *, edict_t *);
extern void use_target_splash(edict_t *, edict_t *, edict_t *);
extern void Use_Target_Tent(edict_t *, edict_t *, edict_t *);
extern void walkmonster_start_go(edict_t *);
const save_ptr_t save_ptrs[] = {
{ P_prethink, misc_viper_bomb_prethink },
{ P_think, AngleMove_Begin },
{ P_think, AngleMove_Done },
{ P_think, AngleMove_Final },
{ P_think, barrel_explode },
{ P_think, bfg_explode },
{ P_think, bfg_think },
{ P_think, button_return },
{ P_think, commander_body_drop },
{ P_think, commander_body_think },
{ P_think, door_go_down },
{ P_think, door_secret_move2 },
{ P_think, door_secret_move4 },
{ P_think, door_secret_move6 },
{ P_think, DoRespawn },
{ P_think, drop_make_touchable },
{ P_think, droptofloor },
{ P_think, flymonster_start_go },
{ P_think, func_clock_think },
{ P_think, func_object_release },
{ P_think, func_timer_think },
{ P_think, func_train_find },
{ P_think, G_FreeEdict },
{ P_think, gib_think },
{ P_think, Grenade_Explode },
{ P_think, M_droptofloor },
{ P_think, M_FliesOff },
{ P_think, M_FliesOn },
{ P_think, MegaHealth_think },
{ P_think, misc_banner_think },
{ P_think, misc_blackhole_think },
{ P_think, misc_easterchick2_think },
{ P_think, misc_easterchick_think },
{ P_think, misc_eastertank_think },
{ P_think, misc_satellite_dish_think },
{ P_think, monster_think },
{ P_think, monster_triggered_spawn },
{ P_think, Move_Begin },
{ P_think, Move_Done },
{ P_think, Move_Final },
{ P_think, multi_wait },
{ P_think, plat_go_down },
{ P_think, SP_CreateCoopSpots },
{ P_think, SP_FixCoopSpots },
{ P_think, swimmonster_start_go },
{ P_think, target_crosslevel_target_think },
{ P_think, target_earthquake_think },
{ P_think, target_explosion_explode },
{ P_think, target_laser_start },
{ P_think, target_laser_think },
{ P_think, target_lightramp_think },
{ P_think, TH_viewthing },
{ P_think, Think_AccelMove },
{ P_think, Think_CalcMoveSpeed },
{ P_think, Think_Delay },
{ P_think, Think_SpawnDoorTrigger },
{ P_think, train_next },
{ P_think, trigger_elevator_init },
{ P_think, turret_breach_finish_init },
{ P_think, turret_breach_think },
{ P_think, turret_driver_link },
{ P_think, turret_driver_think },
{ P_think, walkmonster_start_go },
{ P_blocked, door_blocked },
{ P_blocked, door_secret_blocked },
{ P_blocked, plat_blocked },
{ P_blocked, rotating_blocked },
{ P_blocked, train_blocked },
{ P_blocked, turret_blocked },
{ P_touch, barrel_touch },
{ P_touch, bfg_touch },
{ P_touch, blaster_touch },
{ P_touch, button_touch },
{ P_touch, CTFGrappleTouch },
{ P_touch, door_touch },
{ P_touch, drop_temp_touch },
{ P_touch, func_object_touch },
{ P_touch, gib_touch },
{ P_touch, Grenade_Touch },
{ P_touch, hurt_touch },
{ P_touch, misc_viper_bomb_touch },
{ P_touch, path_corner_touch },
{ P_touch, point_combat_touch },
{ P_touch, rocket_touch },
{ P_touch, rotating_touch },
{ P_touch, teleporter_touch },
{ P_touch, Touch_DoorTrigger },
{ P_touch, Touch_Item },
{ P_touch, Touch_Multi },
{ P_touch, Touch_Plat_Center },
{ P_touch, trigger_gravity_touch },
{ P_touch, trigger_monsterjump_touch },
{ P_touch, trigger_push_touch },
{ P_use, button_use },
{ P_use, commander_body_use },
{ P_use, door_secret_use },
{ P_use, door_use },
{ P_use, func_clock_use },
{ P_use, func_conveyor_use },
{ P_use, func_explosive_spawn },
{ P_use, func_explosive_use },
{ P_use, func_object_use },
{ P_use, func_timer_use },
{ P_use, func_wall_use },
{ P_use, hurt_use },
{ P_use, light_use },
{ P_use, misc_blackhole_use },
{ P_use, misc_satellite_dish_use },
{ P_use, misc_strogg_ship_use },
{ P_use, misc_viper_bomb_use },
{ P_use, misc_viper_use },
{ P_use, monster_triggered_spawn_use },
{ P_use, monster_use },
{ P_use, rotating_use },
{ P_use, target_earthquake_use },
{ P_use, target_laser_use },
{ P_use, target_lightramp_use },
{ P_use, target_string_use },
{ P_use, train_use },
{ P_use, trigger_counter_use },
{ P_use, trigger_crosslevel_trigger_use },
{ P_use, trigger_elevator_use },
{ P_use, trigger_enable },
{ P_use, trigger_key_use },
{ P_use, trigger_relay_use },
{ P_use, Use_Areaportal },
{ P_use, Use_Item },
{ P_use, use_killbox },
{ P_use, Use_Multi },
{ P_use, Use_Plat },
{ P_use, use_target_blaster },
{ P_use, use_target_changelevel },
{ P_use, use_target_explosion },
{ P_use, use_target_goal },
{ P_use, Use_Target_Help },
{ P_use, use_target_secret },
{ P_use, use_target_spawner },
{ P_use, Use_Target_Speaker },
{ P_use, use_target_splash },
{ P_use, Use_Target_Tent },
{ P_pain, player_pain },
{ P_die, barrel_delay },
{ P_die, body_die },
{ P_die, button_killed },
{ P_die, debris_die },
{ P_die, door_killed },
{ P_die, door_secret_die },
{ P_die, func_explosive_explode },
{ P_die, gib_die },
{ P_die, misc_deadsoldier_die },
{ P_die, player_die },
{ P_die, turret_driver_die },
{ P_moveinfo_endfunc, button_done },
{ P_moveinfo_endfunc, button_wait },
{ P_moveinfo_endfunc, door_hit_bottom },
{ P_moveinfo_endfunc, door_hit_top },
{ P_moveinfo_endfunc, door_secret_done },
{ P_moveinfo_endfunc, door_secret_move1 },
{ P_moveinfo_endfunc, door_secret_move3 },
{ P_moveinfo_endfunc, door_secret_move5 },
{ P_moveinfo_endfunc, plat_hit_bottom },
{ P_moveinfo_endfunc, plat_hit_top },
{ P_moveinfo_endfunc, train_wait },
{ P_monsterinfo_checkattack, M_CheckAttack },
};
const int num_save_ptrs = sizeof(save_ptrs) / sizeof(save_ptrs[0]);
